services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        USERNAME: ${USERNAME}
        UID: ${D_UID}
        GID: ${D_GID}
        GIT_USER: ${GIT_USER}
        GIT_EMAIL: ${GIT_EMAIL}
        JAVA_VERSION: ${JAVA_VERSION}
        NODE_VERSION: ${NODE_VERSION}

    restart: always
    volumes:
      - ./:/home/${USERNAME}/app
      - ~/.ssh:/home/${USERNAME}/.ssh

    user: ${D_UID}:${D_GID}

    tty: true
    network_mode: host
    environment:
      DB_URL: cdd
      DB_USERNAME: cdd
      DB_PASSWORD: cdd

  postgres:
    container_name: postgresql_newfy
    image: postgres:${POSTGRES_VERSION}
    network_mode: host
    environment:
      DB_URL: cdd
      POSTGRES_USER: cdd
      POSTGRES_PASSWORD: cdd
      POSTGRES_DB: cdd
    restart: always
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql/data
volumes:
  pg_data: